export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const EXPENSELIST = 'EXPENSELIST';
export const ADDMONTHLYEXPENSE = 'ADDMONTHLYEXPENSE';
export const ADDDAILYEXPENSE = 'ADDDAILYEXPENSE';